# Generated by Django 4.0.4 on 2022-06-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='name',
            new_name='title',
        ),
    ]
