# Generated by Django 4.0.4 on 2022-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0003_alter_todo_options_alter_tracker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
