# Generated by Django 4.0.4 on 2022-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0004_alter_tracker_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='category',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movie', 'Movie'), ('Series', 'Series'), ('Book', 'Book'), ('Manga', 'Manga'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
