# Generated by Django 4.0.4 on 2022-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0005_tracker_category_alter_tracker_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='category',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movie', 'Movie'), ('Series', 'Series'), ('Book', 'Book'), ('Manga', 'Manga'), ('Webtoon', 'Webtoon'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
