# Generated by Django 4.0.4 on 2022-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0006_alter_tracker_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default=3),
        ),
    ]
