# Generated by Django 4.0.4 on 2022-06-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0008_alter_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_time',
        ),
    ]
