# Generated by Django 4.0.4 on 2022-06-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0009_remove_todo_due_date_remove_todo_due_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
