# Generated by Django 4.0.4 on 2022-06-09 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0011_alter_tracker_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 23, 32, 24, 437868, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tracker',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 23, 32, 24, 436868, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tracker',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
