# Generated by Django 4.0.4 on 2022-06-08 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0011_alter_tracker_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 20, 48, 3, 581860)),
        ),
    ]
