# Generated by Django 4.0.4 on 2022-06-08 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0012_todo_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 20, 52, 23, 449862, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 20, 52, 23, 450863, tzinfo=utc)),
        ),
    ]
