# Generated by Django 4.0.4 on 2022-06-08 22:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0013_tracker_added_on_alter_todo_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 22, 51, 1, 146200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 22, 51, 1, 145200, tzinfo=utc)),
        ),
    ]
