# Generated by Django 4.0.4 on 2022-06-22 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0020_alter_todo_added_on_alter_tracker_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 17, 18, 36, 183605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 17, 18, 36, 182606, tzinfo=utc)),
        ),
    ]
