# Generated by Django 4.1.1 on 2022-11-26 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0026_alter_todo_added_on_alter_tracker_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 19, 40, 30, 134093, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 19, 40, 30, 133093, tzinfo=datetime.timezone.utc)),
        ),
    ]
