# Generated by Django 4.0.4 on 2023-12-27 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import seoto.model_validators
import seoto.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhyme', models.CharField(max_length=10, validators=[seoto.model_validators.Validators.str])),
                ('text', models.TextField(validators=[seoto.model_validators.Validators.str])),
                ('word_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rhyme',
                'ordering': ['-timestamp'],
            },
        ),
    ]
