# Generated by Django 6.0.7 on 2026-08-03 00:33

import django.db.models.deletion
import infrastructure.core.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[infrastructure.core.model_validators.Validators.str])),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional line under the section heading.', max_length=300, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Used to deep-link a single answer, e.g. /faq#refund-policy.', max_length=140, unique=True)),
                ('question', models.CharField(max_length=300, validators=[infrastructure.core.model_validators.Validators.str])),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished questions are never served by the API.')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured questions sort ahead of the rest.')),
                ('include_in_schema', models.BooleanField(default=True, help_text='Include in the FAQPage JSON-LD. Turn off for answers too long or link-heavy to be valid structured data.')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='company_faqs.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category__order', '-is_featured', 'order'],
            },
        ),
    ]
