# Generated by Django 6.0 on 2026-03-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
