# Generated by Django 6.0.7 on 2026-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0002_todo_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': [('view_all_todo', 'Can view all todo records')], 'verbose_name_plural': 'todo'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'permissions': [('view_all_tracker', 'Can view all tracker records')], 'verbose_name_plural': 'tracker'},
        ),
    ]
