# Generated by Django 6.0.7 on 2026-08-02 22:41

import django.db.models.deletion
import domains.company.products.models
import infrastructure.core.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=200, validators=[infrastructure.core.model_validators.Validators.str])),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(help_text='The single line shown while the listing is collapsed.', max_length=300)),
                ('body', models.TextField(help_text='What we built — shown when the listing expands.')),
                ('outcome', models.TextField(blank=True, help_text='A result we can stand behind. Leave empty rather than guessing.', null=True)),
                ('live_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('Draft', 'DRAFT'), ('In Progress', 'IN_PROGRESS'), ('Launched', 'LAUNCHED'), ('Archived', 'ARCHIVED'), ('Managed', 'MANAGED')], default='DRAFT', max_length=50)),
                ('launched_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-launched_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, validators=[infrastructure.core.model_validators.Validators.str])),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name_plural': 'Product Tags',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=domains.company.products.models.product_image_path)),
                ('alt_text', models.CharField(max_length=250, validators=[infrastructure.core.model_validators.Validators.str])),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company_products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='company_products.producttag'),
        ),
    ]
