# Generated by Django 6.0.7 on 2026-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('LAUNCHED', 'Launched'), ('ARCHIVED', 'Archived'), ('MANAGED', 'Managed')], default='DRAFT', max_length=50),
        ),
    ]
