# Generated by Django 6.0.7 on 2026-08-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_products', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', 'order', '-launched_on']},
        ),
        migrations.AddField(
            model_name='product',
            name='contributors',
            field=models.JSONField(blank=True, default=list, help_text='Names of people who worked on it, e.g. ["Ada Lovelace"].'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products sort ahead of the rest.'),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsors',
            field=models.JSONField(blank=True, default=list, help_text='Names of funding or backing organisations.'),
        ),
    ]
