# Generated by Django 6.0 on 2026-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='picture_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/thumbs'),
        ),
    ]
