# Generated by Django 5.0 on 2023-12-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBreakfast', models.BooleanField(default=False)),
                ('isBrunch', models.BooleanField(default=False)),
                ('isLunch', models.BooleanField(default=False)),
                ('isDinner', models.BooleanField(default=False)),
                ('isExtra', models.BooleanField(default=False)),
                ('isFancy', models.BooleanField(default=False)),
                ('isAvailable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('nutrients', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('cooking_duration', models.CharField(blank=True, max_length=40)),
                ('main_img', models.ImageField(blank=True, upload_to='food')),
                ('img_1', models.ImageField(blank=True, upload_to='food')),
                ('img_2', models.ImageField(blank=True, upload_to='food')),
                ('img_3', models.ImageField(blank=True, upload_to='food')),
            ],
        ),
    ]
