# Generated by Django 5.2.5 on 2025-09-28 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_user_preferences(apps, schema_editor):
    # Access historical versions of models
    Meal = apps.get_model('foodie', 'meal')
    UserPreference = apps.get_model('foodie', 'userPreference')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    # For each user, copy existing Meal time flags into a per-meal userPreference row
    batch = []
    # Using iterators to avoid loading everything in memory at once
    users = User.objects.all().iterator()
    for user in users:
        meals_iter = Meal.objects.all().iterator()
        for m in meals_iter:
            batch.append(UserPreference(
                user_id=user.id,
                meal_id=m.id,
                isBreakfast=getattr(m, 'isBreakfast', False),
                isBrunch=getattr(m, 'isBrunch', False),
                isLunch=getattr(m, 'isLunch', False),
                isDinner=getattr(m, 'isDinner', False),
                isExtra=getattr(m, 'isExtra', False),
                isFancy=getattr(m, 'isFancy', False),
                isAvailable=getattr(m, 'isAvailable', True),
            ))
            if len(batch) >= 1000:
                UserPreference.objects.bulk_create(batch, ignore_conflicts=True)
                batch = []
    if batch:
        UserPreference.objects.bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, create the new userPreference model so we can populate it
        migrations.CreateModel(
            name='userPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBreakfast', models.BooleanField(default=False)),
                ('isBrunch', models.BooleanField(default=False)),
                ('isLunch', models.BooleanField(default=False)),
                ('isDinner', models.BooleanField(default=False)),
                ('isExtra', models.BooleanField(default=False)),
                ('isFancy', models.BooleanField(default=False)),
                ('isAvailable', models.BooleanField(default=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='foodie.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meal')},
            },
        ),
        # Next, populate userPreference from existing Meal flags for every user
        migrations.RunPython(populate_user_preferences, migrations.RunPython.noop),
        # Finally, drop the old fields from Meal
        migrations.RemoveField(
            model_name='meal',
            name='isAvailable',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='isBreakfast',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='isBrunch',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='isDinner',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='isExtra',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='isFancy',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='isLunch',
        ),
    ]
