# Generated by Django 6.0 on 2026-03-01 21:43

import foodie.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_meal_created_by_meal_is_public_alter_meal_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='img_1',
            field=models.ImageField(blank=True, upload_to=functools.partial(foodie.models.meal_image_path, slot=2)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='img_2',
            field=models.ImageField(blank=True, upload_to=functools.partial(foodie.models.meal_image_path, slot=3)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='img_3',
            field=models.ImageField(blank=True, upload_to=functools.partial(foodie.models.meal_image_path, slot=4)),
        ),
    ]
