# Generated by Django 6.0 on 2026-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_alter_meal_img_1_alter_meal_img_2_alter_meal_img_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='main_img_thumbnail',
            field=models.ImageField(blank=True, upload_to='food/thumbs'),
        ),
    ]
