# Generated by Django 6.0 on 2026-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0007_redesign_mealtime_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_fancy',
            field=models.BooleanField(default=False),
        ),
    ]
