# Generated by Django 6.0 on 2026-03-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0008_add_meal_is_fancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealOrder',
        ),
    ]
