# Generated by Django 6.0 on 2026-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0009_remove_mealorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='default_preference',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='default_preference',
            new_name='categories',
        ),
    ]
