# Generated by Django 5.2.5 on 2025-10-27 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_remove_meal_isavailable_remove_meal_isbreakfast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Optional details or instructions for this order')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('not_available', models.BooleanField(default=False, help_text='If checked, this order can be edited by the user to choose alternatives.')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to='foodie.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
    ]
