# Generated by Django 6.0 on 2026-05-05 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0010_change_default_preference_to_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foodie.meal')),
                ('option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foodie.meal')),
                ('option_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foodie.meal')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_suggestions', to='foodie.mealtimeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='foodie_dail_user_id_60e171_idx')],
                'unique_together': {('user', 'date', 'slot')},
            },
        ),
    ]
