# Generated by Django 6.0.7 on 2026-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_dailymealsuggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymealsuggestion',
            options={'permissions': [('view_all_dailymealsuggestion', 'Can view all DailyMealSuggestion records')]},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'permissions': [('view_all_meal', 'Can view all meal records')]},
        ),
        migrations.AlterModelOptions(
            name='usermealschedule',
            options={'permissions': [('view_all_usermealschedule', 'Can view all UserMealSchedule records')]},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'permissions': [('view_all_userpreference', 'Can view all userPreference records')]},
        ),
    ]
