# Generated by Django 4.0.4 on 2022-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='picture',
            field=models.FileField(default='../seoto/static/img/profile_pic.png', upload_to='media/accounts/<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
