# Generated by Django 4.0.4 on 2022-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='picture',
            field=models.FileField(default='../seoto/static/img/profile_pic.png', upload_to='media/accounts/%Y-%m-%d'),
        ),
    ]
