# Generated by Django 4.0.4 on 2022-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
