# Generated by Django 4.0.4 on 2022-06-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='picture',
            field=models.ImageField(upload_to='accounts/%Y-%m-%d'),
        ),
    ]
