# Generated by Django 4.0.2 on 2024-06-08 13:55

import accounts.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(accounts.utils.user_directory_file_path, *(), **{'prefix': 'accounts/%Y-%m-%d'})),
        ),
    ]
