# Generated by Django 6.0 on 2026-05-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profile_picture_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
    ]
