# Generated by Django 5.0 on 2023-12-25 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('label', models.CharField(default='Developer stack', max_length=100)),
                ('languages', models.TextField(blank=True, null=True)),
                ('frameworks', models.TextField(blank=True, null=True)),
                ('databases', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'stack',
            },
        ),
    ]
