# Generated by Django 4.0.4 on 2023-12-27 22:03

from django.db import migrations, models

import seoto.model_validators
import seoto.utils


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, validators=[seoto.model_validators.Validators.str]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(validators=[seoto.model_validators.Validators.str]),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=200, validators=[seoto.model_validators.Validators.str]),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200, validators=[seoto.model_validators.Validators.str]),
        ),
    ]
