# Generated by Django 4.0.2 on 2024-06-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_message_email_alter_message_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=250)),
                ('certificate_title', models.CharField(max_length=250)),
                ('certificate_type', models.CharField(choices=[('High School Diploma', 'HIGH_SCHOOL_DIPLOMA'), ('Associate Degree', 'ASSOCIATE_DEGREE'), ("Bachelor's Degree", 'BACHELORS_DEGREE'), ("Master's Degree", 'MASTERS_DEGREE'), ('Doctorate Degree', 'DOCTORATE_DEGREE'), ('Professional Degree', 'PROFESSIONAL_DEGREE'), ('Certificate', 'CERTIFICATE'), ('Diploma', 'DIPLOMA'), ('Postgraduate Certificate', 'POSTGRADUATE_CERTIFICATE'), ('Postgraduate Diploma', 'POSTGRADUATE_DIPLOMA'), ('Trade Certificate', 'TRADE_CERTIFICATE'), ('Vocational Certificate', 'VOCATIONAL_CERTIFICATE'), ('Honorary Doctorate', 'HONORARY_DOCTORATE'), ('Other', 'OTHER')], max_length=250)),
                ('other_certificate_type', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('show_email', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=17)),
                ('show_phone', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('show_address', models.BooleanField(default=True)),
                ('nationality', models.CharField(blank=True, max_length=250, null=True)),
                ('show_nationality', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('show_date_of_birth', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(upload_to='author/profile_picture')),
                ('about', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Intro',
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('employer', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntroLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=1000)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='author.intro')),
            ],
            options={
                'verbose_name_plural': 'IntroLinks',
            },
        ),
    ]
