# Generated by Django 4.0.2 on 2024-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_message_email_alter_message_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=250)),
                ('certificate_title', models.CharField(max_length=250)),
                ('certificate_type', models.CharField(choices=[('HIGH_SCHOOL_DIPLOMA', 'High School Diploma'), ('ASSOCIATE_DEGREE', 'Associate Degree'), ('BACHELORS_DEGREE', "Bachelor's Degree"), ('MASTERS_DEGREE', "Master's Degree"), ('DOCTORATE_DEGREE', 'Doctorate Degree'), ('PROFESSIONAL_DEGREE', 'Professional Degree'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('POSTGRADUATE_CERTIFICATE', 'Postgraduate Certificate'), ('POSTGRADUATE_DIPLOMA', 'Postgraduate Diploma'), ('TRADE_CERTIFICATE', 'Trade Certificate'), ('VOCATIONAL_CERTIFICATE', 'Vocational Certificate'), ('HONORARY_DOCTORATE', 'Honorary Doctorate'), ('OTHER', 'Other')], max_length=250)),
                ('other_certificate_type', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='IntroLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'IntroLinks',
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('employer', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=17)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('nationality', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_image', models.ImageField(upload_to='author/profile_picture')),
                ('about', models.TextField(blank=True, null=True)),
                ('links', models.ManyToManyField(to='author.IntroLinks')),
            ],
        ),
    ]
