# Generated by Django 4.0.2 on 2024-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_education_intro_jobexperience_introlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexperience',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
