# Generated by Django 4.0.4 on 2022-06-22 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_alter_contact_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 15, 2, 35, 890072, tzinfo=utc)),
        ),
    ]
