# Generated by Django 4.1.1 on 2022-11-26 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0012_alter_contact_submitted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_on', models.DateTimeField(default=datetime.datetime(2022, 11, 26, 18, 58, 54, 52358, tzinfo=datetime.timezone.utc))),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
