# Generated by Django 4.1.1 on 2022-11-26 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0013_message_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.TextField(blank=True, null=True)),
                ('frameworks', models.TextField(blank=True, null=True)),
                ('databases', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 19, 6, 10, 462661, tzinfo=datetime.timezone.utc)),
        ),
    ]
