# Generated by Django 4.1.1 on 2022-11-26 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0014_stacks_alter_message_submitted_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stacks',
            new_name='stack',
        ),
        migrations.AlterField(
            model_name='message',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 19, 10, 41, 261073, tzinfo=datetime.timezone.utc)),
        ),
    ]
