# Generated by Django 4.1.1 on 2022-11-26 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0015_rename_stacks_stack_alter_message_submitted_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name_plural': 'stack'},
        ),
        migrations.AddField(
            model_name='stack',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stack',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 19, 35, 50, 428334, tzinfo=datetime.timezone.utc)),
        ),
    ]
