# Generated by Django 4.1.1 on 2022-11-26 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0016_alter_stack_options_stack_is_active_stack_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 19, 40, 30, 128093, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stack',
            name='label',
            field=models.CharField(default='Developer stack', max_length=100),
        ),
    ]
