# Generated by Django 3.2.11 on 2022-12-27 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0017_alter_message_submitted_on_alter_stack_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 19, 57, 41, 232982, tzinfo=utc)),
        ),
    ]
