# Generated by Django 3.2.11 on 2022-12-27 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0018_alter_message_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
