# Generated by Django 5.2 on 2025-04-25 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Post Tags',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'author', 'is_public')},
        ),
        migrations.CreateModel(
            name='PostReadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('users', models.ManyToManyField(blank=True, related_name='post_read_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_posts', to='blog.postreadgroup'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.posttags'),
        ),
    ]
