# Generated by Django 5.2.5 on 2025-08-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttags',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
