# Generated by Django 5.2.5 on 2025-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posttags_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
