# Generated by Django 6.0.7 on 2026-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('view_all_post', 'Can view all Post records')]},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'permissions': [('view_all_postcomment', 'Can view all PostComment records')]},
        ),
        migrations.AlterModelOptions(
            name='postreadgroup',
            options={'permissions': [('view_all_postreadgroup', 'Can view all PostReadGroup records')]},
        ),
    ]
