# Generated by Django 5.2.5 on 2025-12-01 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex color code (e.g., #007bff)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#212529', help_text='Body text color', max_length=7)),
                ('text_head_color', models.CharField(default='#000000', help_text='Headers and labels color', max_length=7)),
                ('navbar_bg', models.CharField(default='#f8f9fa', help_text='Navbar background color', max_length=7)),
                ('navbar_text', models.CharField(default='#000000', help_text='Navbar text color', max_length=7)),
                ('btn_success_bg', models.CharField(default='#28a745', help_text='Success button background', max_length=7)),
                ('btn_success_text', models.CharField(default='#ffffff', help_text='Success button text', max_length=7)),
                ('btn_danger_bg', models.CharField(default='#dc3545', help_text='Danger button background', max_length=7)),
                ('btn_danger_text', models.CharField(default='#ffffff', help_text='Danger button text', max_length=7)),
                ('btn_warning_bg', models.CharField(default='#ffc107', help_text='Warning button background', max_length=7)),
                ('btn_warning_text', models.CharField(default='#000000', help_text='Warning button text', max_length=7)),
                ('btn_info_bg', models.CharField(default='#17a2b8', help_text='Info button background', max_length=7)),
                ('btn_info_text', models.CharField(default='#ffffff', help_text='Info button text', max_length=7)),
                ('btn_secondary_bg', models.CharField(default='#6c757d', help_text='Secondary button background', max_length=7)),
                ('btn_secondary_text', models.CharField(default='#ffffff', help_text='Secondary button text', max_length=7)),
                ('card_bg_color', models.CharField(default='#ffffff', help_text='Card background color', max_length=7)),
                ('card_header_bg_color', models.CharField(default='#f8f9fa', help_text='Card header background', max_length=7)),
                ('card_text_color', models.CharField(default='#212529', help_text='Card text color', max_length=7)),
                ('is_official', models.BooleanField(default=False, help_text='Official theme created by admin')),
                ('is_public', models.BooleanField(default=False, help_text='User wants to share this theme')),
                ('is_public_verified', models.BooleanField(default=False, help_text='Admin has verified this public theme')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured theme highlighted by admin')),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-is_official', '-rating_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_using_preset', models.BooleanField(default=True)),
                ('custom_primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_text_head_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_navbar_bg', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_navbar_text', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_success_bg', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_success_text', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_danger_bg', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_danger_text', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_warning_bg', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_warning_text', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_info_bg', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_info_text', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_secondary_bg', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_btn_secondary_text', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_card_bg_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_card_header_bg_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_card_text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_using', to='theme.themepreset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='theme.themepreset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'theme')},
            },
        ),
    ]
