# Generated by Django 6.0.7 on 2026-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themepreset',
            options={'ordering': ['-is_featured', '-is_official', '-rating_count', '-created_at'], 'permissions': [('view_all_themepreset', 'Can view all ThemePreset records')]},
        ),
        migrations.AlterModelOptions(
            name='themerating',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_themerating', 'Can view all ThemeRating records')]},
        ),
        migrations.AlterModelOptions(
            name='usertheme',
            options={'permissions': [('view_all_usertheme', 'Can view all UserTheme records')]},
        ),
    ]
