# Generated by Django 6.0.7 on 2026-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwa', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_notification', 'Can view all Notification records')], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'permissions': [('view_all_pushsubscription', 'Can view all PushSubscription records')], 'verbose_name': 'Push Subscription', 'verbose_name_plural': 'Push Subscriptions'},
        ),
    ]
