# Generated by Django 5.2.5 on 2025-08-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0002_account_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('CHECKING', 'CHECKING'), ('CREDIT_CARD', 'CREDIT_CARD'), ('CASH', 'CASH')], default='SAVINGS', max_length=100),
        ),
    ]
