# Generated by Django 5.2.5 on 2025-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0004_alter_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
