# Generated by Django 5.2.5 on 2025-10-16 08:09

from django.db import migrations


def populate_transaction_time(apps, schema_editor):
    """Copy created_at to transaction_time for all transactions without transaction_time"""
    Transaction = apps.get_model('spending_tracker', 'Transaction')

    # Get all transactions where transaction_time is null
    transactions_to_update = Transaction.objects.filter(transaction_time__isnull=True)
    count = transactions_to_update.count()

    if count > 0:
        print(f"Populating transaction_time for {count} transactions...")

        # Update in bulk for performance
        for transaction in transactions_to_update:
            transaction.transaction_time = transaction.created_at

        Transaction.objects.bulk_update(transactions_to_update, ['transaction_time'], batch_size=500)
        print(f"Successfully populated transaction_time for {count} transactions.")
    else:
        print("No transactions need transaction_time population.")


def reverse_populate_transaction_time(apps, schema_editor):
    """Reverse migration - set transaction_time to null for all transactions"""
    Transaction = apps.get_model('spending_tracker', 'Transaction')
    Transaction.objects.all().update(transaction_time=None)


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0007_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_transaction_time, reverse_populate_transaction_time),
    ]
