# Generated by Django 6.0 on 2026-07-03 21:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0012_transaction_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='GHS', max_length=3)),
                ('details', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='YEARLY', max_length=10)),
                ('custom_type', models.CharField(blank=True, choices=[('DAYS_OF_WEEK', 'Specific days of the week'), ('DAYS_OF_MONTH', 'Specific days of the month')], max_length=20, null=True)),
                ('custom_weekdays', models.JSONField(blank=True, default=list, help_text='0=Monday .. 6=Sunday')),
                ('custom_month_days', models.JSONField(blank=True, default=list, help_text='Day-of-month numbers, 1-31')),
                ('renewal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('next_run_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_auto_renew', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='spending_tracker.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='spending_tracker.category')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_recurring_transfers', to='spending_tracker.account')),
                ('tags', models.ManyToManyField(blank=True, related_name='recurring_transactions', to='spending_tracker.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransactionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('AUTO_CREATED', 'Auto Created'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('recurring_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='spending_tracker.recurringtransaction')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_occurrence', to='spending_tracker.transaction')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['is_active', 'next_run_date'], name='spending_tr_is_acti_2b5408_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active'], name='spending_tr_user_id_10a198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recurringtransactionoccurrence',
            unique_together={('recurring_transaction', 'scheduled_date')},
        ),
    ]
