# Generated by Django 5.2.14 on 2026-07-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0013_recurringtransaction_recurringtransactionoccurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='notification_note',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
