# Generated by Django 6.0.7 on 2026-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0014_recurringtransaction_notification_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'permissions': [('view_all_account', 'Can view all Account records')]},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['label'], 'permissions': [('view_all_category', 'Can view all Category records')], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'ordering': ['next_run_date'], 'permissions': [('view_all_recurringtransaction', 'Can view all RecurringTransaction records')]},
        ),
        migrations.AlterModelOptions(
            name='recurringtransactionoccurrence',
            options={'ordering': ['-scheduled_date'], 'permissions': [('view_all_recurringtransactionoccurrence', 'Can view all RecurringTransactionOccurrence records')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label'], 'permissions': [('view_all_tag', 'Can view all Tag records')]},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_time', 'account__name', 'amount', 'reference'], 'permissions': [('view_all_transaction', 'Can view all Transaction records')]},
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'permissions': [('view_all_userpreferences', 'Can view all UserPreferences records')], 'verbose_name_plural': 'User Preferences'},
        ),
    ]
