# Generated by Django 6.0.7 on 2026-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymes', '0002_alter_rhyme_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rhyme',
            options={'ordering': ['-timestamp'], 'permissions': [('view_all_rhyme', 'Can view all Rhyme records')]},
        ),
    ]
