# Generated by Django 6.0.7 on 2026-08-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate_type',
            field=models.CharField(choices=[('High School Diploma', 'High School Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate Degree', 'Doctorate Degree'), ('Professional Degree', 'Professional Degree'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Postgraduate Certificate', 'Postgraduate Certificate'), ('Postgraduate Diploma', 'Postgraduate Diploma'), ('Trade Certificate', 'Trade Certificate'), ('Vocational Certificate', 'Vocational Certificate'), ('Honorary Doctorate', 'Honorary Doctorate'), ('Other', 'Other')], max_length=250),
        ),
    ]
