# Generated by Django 6.0.7 on 2026-09-05 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('reference_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='GHS', max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('hometown', models.CharField(blank=True, max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='staff/profile_picture')),
                ('about', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=250)),
                ('employer', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_experience', to='company_staff.member')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='company_staff.member')),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('school', models.CharField(max_length=250)),
                ('certificate_title', models.CharField(max_length=250)),
                ('certificate_type', models.CharField(choices=[('High School Diploma', 'High School Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate Degree', 'Doctorate Degree'), ('Professional Degree', 'Professional Degree'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Postgraduate Certificate', 'Postgraduate Certificate'), ('Postgraduate Diploma', 'Postgraduate Diploma'), ('Trade Certificate', 'Trade Certificate'), ('Vocational Certificate', 'Vocational Certificate'), ('Honorary Doctorate', 'Honorary Doctorate'), ('Other', 'Other')], max_length=250)),
                ('other_certificate_type', models.CharField(blank=True, max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='company_staff.member')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('course_name', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('awarded_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='company_staff.member')),
            ],
            options={
                'ordering': ['-awarded_on', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('lead', 'Lead')], default='member', max_length=20)),
                ('joined_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='company_staff.member')),
            ],
            options={
                'ordering': ['-joined_on'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='teams', through='company_staff.Membership', to='company_staff.member')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='company_staff.team'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('mobile', 'Mobile'), ('landline', 'Landline'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('usage', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('emergency', 'Emergency')], default='personal', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company_staff.member')),
            ],
            options={
                'ordering': ['-is_primary', 'channel', 'value'],
                'constraints': [models.UniqueConstraint(fields=('member', 'channel', 'value'), name='unique_member_contact_value'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member', 'channel'), name='unique_primary_contact_per_channel')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('residential', 'Residential'), ('postal', 'Postal'), ('hometown', 'Hometown')], default='residential', max_length=20)),
                ('house_number', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('digital_address', models.CharField(blank=True, max_length=15)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company_staff.member')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_primary', 'city', 'street'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member',), name='unique_primary_address_per_member')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='GHS', max_length=3)),
                ('effective_from', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company_staff.member')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='company_staff.position')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
                'constraints': [models.UniqueConstraint(fields=('member', 'effective_from'), name='unique_member_assignment_date')],
            },
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('tools', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='company_staff.member')),
            ],
            options={
                'verbose_name_plural': 'Specialisations',
                'ordering': ['order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('member', 'name'), name='unique_member_specialisation')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_on__isnull', True)), fields=('team', 'member'), name='unique_active_team_membership'),
        ),
    ]
