# Generated by Django 6.0.7 on 2026-09-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_staff', '0002_seed_positions_and_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_issued', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Staff ID sequence',
                'verbose_name_plural': 'Staff ID sequence',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='staff_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
