# Generated by Django 6.0.7 on 2026-09-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_staff', '0003_staffidsequence_alter_member_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='staff_id',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Staff ID'),
        ),
    ]
