# Generated by Django 6.0.7 on 2026-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_staff', '0004_alter_member_staff_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_member_assignment_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Leave blank while the member still holds it.', null=True),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('member', 'position', 'effective_from'), name='unique_member_position_start'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='assignment_ends_after_it_starts'),
        ),
    ]
