# Generated by Django 5.2.5 on 2025-09-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0003_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='GHS', max_length=3),
        ),
    ]
