# Generated by Django 5.2.5 on 2025-10-16 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0006_alter_account_is_default_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_time', 'account__name', 'amount', 'reference']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='spending_tr_created_918eec_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='spending_tr_account_4bd6b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='spending_tr_categor_f0d4c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='spending_tr_mode_638463_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='spending_tr_created_94a2a4_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-transaction_time', 'mode'], name='spending_tr_transac_9d0dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-transaction_time'], name='spending_tr_account_6356f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', '-transaction_time'], name='spending_tr_categor_3a39fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['mode', '-transaction_time', 'account'], name='spending_tr_mode_f55c09_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-transaction_time', 'account', 'mode'], name='spending_tr_transac_b0e77f_idx'),
        ),
    ]
