# Generated by Django 6.0 on 2026-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_tracker', '0011_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, help_text='Receipt image (JPEG, PNG, WebP, GIF) or PDF', null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
